stages:
  - build
  - test

before_script:
  - echo "Start CI"

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

test:
  stage: test
  script:
    - ./gradlew check


after_script:
  - echo "End CI"